// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC94EUADS_HN6ZSVb4r4JP7ZIRmgNeOMlM',
    appId: '1:432541681833:web:df8a99197c9a88a41741b8',
    messagingSenderId: '432541681833',
    projectId: 'login-firebase-a1049',
    authDomain: 'login-firebase-a1049.firebaseapp.com',
    storageBucket: 'login-firebase-a1049.appspot.com',
    measurementId: 'G-HYBKSNDXQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxGxwhgaDVforeiCxFMUnytPna1-mtsA',
    appId: '1:432541681833:android:a93dd063740358dc1741b8',
    messagingSenderId: '432541681833',
    projectId: 'login-firebase-a1049',
    storageBucket: 'login-firebase-a1049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqW7Rs7QLDo2oU-bR6MQtA9Al2wXd1-s',
    appId: '1:432541681833:ios:f945f30a95b6c59c1741b8',
    messagingSenderId: '432541681833',
    projectId: 'login-firebase-a1049',
    storageBucket: 'login-firebase-a1049.appspot.com',
    androidClientId: '432541681833-ef8hjn2d4177utuubjbakc6dk9m9b3rg.apps.googleusercontent.com',
    iosClientId: '432541681833-67hlpu898ef3ss03qkb4ejh7vvpmp72i.apps.googleusercontent.com',
    iosBundleId: 'com.example.logicaltestmainMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwqW7Rs7QLDo2oU-bR6MQtA9Al2wXd1-s',
    appId: '1:432541681833:ios:beb0bd61960e5a9c1741b8',
    messagingSenderId: '432541681833',
    projectId: 'login-firebase-a1049',
    storageBucket: 'login-firebase-a1049.appspot.com',
    androidClientId: '432541681833-ef8hjn2d4177utuubjbakc6dk9m9b3rg.apps.googleusercontent.com',
    iosClientId: '432541681833-47oosfg50movno0mrcop8r9tdnnsv0oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.logicaltestmainMain.RunnerTests',
  );
}
